import os
import logging
import time
import re

import requests
from dotenv import load_dotenv

load_dotenv()

DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY", "")
logger = logging.getLogger(__name__)


def _make_query_plan(key: str, sql: str, summary: str):
    return type(
        "QueryPlan",
        (),
        {
            "key": key,
            "sql": sql,
            "summary": summary,
        },
    )()


def _strip_sql_fences(sql: str) -> str:
    return sql.replace("```sql", "").replace("```", "").strip()


def _request_llm_sql(full_prompt: str, fallback_sql: str, fallback_summary: str):
    started = time.perf_counter()

    if not DEEPSEEK_API_KEY:
        logger.info("llm.fallback missing_api_key duration_sec=%.2f", time.perf_counter() - started)
        return _make_query_plan("fallback", fallback_sql, fallback_summary)

    headers = {
        "Authorization": f"Bearer {DEEPSEEK_API_KEY}",
        "Content-Type": "application/json",
    }

    data = {
        "model": "deepseek-chat",
        "messages": [{"role": "user", "content": full_prompt}],
        "temperature": 0,
        "max_tokens": 300,
    }

    try:
        response = requests.post(
            "https://api.deepseek.com/v1/chat/completions",
            headers=headers,
            json=data,
            timeout=10,
        )
        if response.status_code == 200:
            sql = _strip_sql_fences(response.json()["choices"][0]["message"]["content"])
            logger.info(
                "llm.success status=%d duration_sec=%.2f",
                response.status_code,
                time.perf_counter() - started,
            )
            return _make_query_plan("query", sql, "Generated by DeepSeek")

        logger.warning(
            "llm.http_error status=%d duration_sec=%.2f",
            response.status_code,
            time.perf_counter() - started,
        )
        return _make_query_plan("fallback", fallback_sql, f"API error: {response.status_code}")
    except Exception as e:
        logger.exception(
            "llm.exception duration_sec=%.2f error=%s",
            time.perf_counter() - started,
            e,
        )
        return _make_query_plan("fallback", fallback_sql, f"Error: {str(e)[:50]}")

def build_schema_context():
    return """
Tables in yelp_db:

1. business
   - business_id (string)
   - name (string)
   - address (string)
   - city (string)
   - state (string)
   - postal_code (string)
   - latitude (float)
   - longitude (float)
   - stars (float)
   - review_count (int)
   - is_open (tinyint)
   - attributes (string)
   - categories (string)
   - hours (string)

2. review
   - review_id (string)
   - rev_user_id (string)
   - rev_business_id (string)
   - rev_stars (int)
   - rev_useful (int)
   - rev_funny (int)
   - rev_cool (int)
   - rev_text (string)
   - rev_timestamp (string)
   - rev_date (date)

3. users
   - user_id (string)
   - user_name (string)
   - user_review_count (int)
   - user_yelping_since (string)
   - user_friends (string)
   - user_useful (int)
   - user_funny (int)
   - user_cool (int)
   - user_fans (int)
   - user_elite (string)
   - user_average_stars (float)

4. checkin
   - business_id (string)
   - checkin_dates (string)

5. tip
   - text (string)
   - date (string)
   - compliment_count (int)
  - business_id (string)
   - user_id (string)
"""

def generate_query_plan(prompt, schema_context):
    started = time.perf_counter()
    full_prompt = f"""Convert this question to Hive SQL. Return ONLY the SQL.

Schema:
{schema_context}

Question: {prompt}

Instructions:
- Extract the business type from the question (e.g., Mexican, Chinese, Bars, Salons, Pizza, Sushi, Cafes, Bakeries, etc.)
- Extract the city from the question if mentioned (e.g., Philadelphia, Tampa, New Orleans, etc.)
- Extract the rating if mentioned (e.g., 5 stars, 4 stars, highest rated)
- Extract the review count if mentioned (e.g., over 100 reviews, most reviews)
- Build a SQL query that:
  - Filters by city: WHERE lower(city) = 'cityname' (if city mentioned)
    - Filters by business type: WHERE lower(categories) LIKE '%businesstype%'
    - Avoid adding extra "restaurant" filters unless explicitly asked; just match the cuisine/term
    - Filters by stars: WHERE stars >= rating (if rating mentioned)
    - Orders by stars DESC or review_count DESC based on the question
    - Limits to 10 rows

Examples:
- "Show me top 5 Mexican restaurants" → WHERE lower(categories) LIKE '%mexican%'
- "Show me best bars in Tampa" → WHERE lower(city) = 'tampa' AND lower(categories) LIKE '%bars%' AND lower(categories) NOT LIKE '%barbecue%'
- "Show me Italian restaurants" → WHERE lower(categories) LIKE '%italian%' AND lower(categories) LIKE '%restaurant%'
- "Show me pizza places" → WHERE lower(categories) LIKE '%pizza%'
- "Show me salons" → WHERE lower(categories) LIKE '%salons%' OR lower(categories) LIKE '%hair%'
- "Show me coffee shops" → WHERE lower(categories) LIKE '%coffee%'

SQL:"""

    plan = _request_llm_sql(
        full_prompt=full_prompt,
        fallback_sql="SELECT name, city, stars FROM business LIMIT 10",
        fallback_summary="Missing DEEPSEEK_API_KEY; using fallback",
    )
    # Remove over-restrictive restaurant filter that can zero valid cuisine results
    sql_lower = plan.sql.lower()
    if "like '%restaurant%'" in sql_lower and "like '%mexican%'" in sql_lower:
        plan.sql = sql_lower.replace("and lower(categories) like '%restaurant%'", "")
        plan.sql = plan.sql.replace("  ", " ").strip()

    logger.info("llm.plan_ready duration_sec=%.2f summary=%s", time.perf_counter() - started, plan.summary)
    return plan


def generate_corrected_query_plan(prompt, schema_context, failed_sql, error_message):
    started = time.perf_counter()
    trimmed_error = str(error_message).strip()[:1200]
    full_prompt = f"""You are repairing a Hive SQL query.

Return ONLY the corrected SQL.

Original user question:
{prompt}

Schema:
{schema_context}

Failed SQL:
{failed_sql}

Execution error:
{trimmed_error}

Requirements:
- Fix the SQL so it runs on Hive for the given schema.
- Preserve the user's intent.
- Only output executable SQL.
- Use real column names from the schema above.
- Keep the query read-only.
- Prefer simple SELECT statements and include a LIMIT when appropriate.

Corrected SQL:"""

    plan = _request_llm_sql(
        full_prompt=full_prompt,
        fallback_sql=failed_sql,
        fallback_summary="Automatic correction unavailable; returning original SQL",
    )
    plan.summary = "Generated by DeepSeek (auto-corrected after execution error)"
    logger.info(
        "llm.repair_ready duration_sec=%.2f summary=%s",
        time.perf_counter() - started,
        plan.summary,
    )
    return plan


def detect_fast_path_query(prompt: str):
    prompt_clean = " ".join(str(prompt or "").strip().split())
    prompt_lower = prompt_clean.lower()

    patterns = [
        (
            re.search(r"\b(show|list).*(5|five).*(rows?|businesses?).*\bbusiness\b", prompt_lower),
            _make_query_plan(
                "fast_path",
                "SELECT name, city, state, stars, review_count FROM business LIMIT 5",
                "Fast path: sample businesses",
            ),
        ),
        (
            "average business rating by state" in prompt_lower
            or "average rating by state" in prompt_lower
            or "avg rating by state" in prompt_lower,
            _make_query_plan(
                "fast_path",
                """
                SELECT state, ROUND(AVG(stars), 2) AS avg_stars, COUNT(*) AS business_count
                FROM business
                WHERE state IS NOT NULL AND TRIM(state) != ''
                GROUP BY state
                ORDER BY avg_stars DESC, business_count DESC
                LIMIT 10
                """.strip(),
                "Fast path: average stars by state",
            ),
        ),
        (
            "most elite users" in prompt_lower and "cities" in prompt_lower,
            _make_query_plan(
                "fast_path",
                """
                SELECT u.city, COUNT(*) AS elite_users
                FROM (
                    SELECT city, user_id
                    FROM business b
                    JOIN review r ON b.business_id = r.rev_business_id
                    JOIN users u ON r.rev_user_id = u.user_id
                    WHERE u.user_elite IS NOT NULL AND TRIM(u.user_elite) != '' AND LOWER(u.user_elite) != 'null'
                ) u
                GROUP BY u.city
                HAVING u.city IS NOT NULL AND TRIM(u.city) != ''
                ORDER BY elite_users DESC
                LIMIT 10
                """.strip(),
                "Fast path: elite users by city",
            ),
        ),
        (
            ("top 5 highest-rated mexican restaurants" in prompt_lower or "top mexican" in prompt_lower)
            and "philadelphia" in prompt_lower,
            _make_query_plan(
                "fast_path",
                """
                SELECT name, city, state, stars, review_count
                FROM business
                WHERE LOWER(city) = 'philadelphia'
                  AND LOWER(categories) LIKE '%mexican%'
                  AND review_count > 500
                ORDER BY stars DESC, review_count DESC
                LIMIT 5
                """.strip(),
                "Fast path: top Mexican restaurants in Philadelphia",
            ),
        ),
        (
            ("top cities" in prompt_lower or "cities have the most businesses" in prompt_lower or "cities by number of businesses" in prompt_lower),
            _make_query_plan(
                "fast_path",
                """
                SELECT city, COUNT(*) AS business_count
                FROM business
                WHERE city IS NOT NULL AND TRIM(city) != ''
                GROUP BY city
                ORDER BY business_count DESC
                LIMIT 10
                """.strip(),
                "Fast path: top cities by business count",
            ),
        ),
        (
            ("top categories" in prompt_lower or "business categories" in prompt_lower),
            _make_query_plan(
                "fast_path",
                """
                SELECT category, COUNT(*) AS business_count
                FROM (
                    SELECT explode(split(categories, ',')) AS category
                    FROM business
                    WHERE categories IS NOT NULL AND TRIM(categories) != ''
                ) exploded
                WHERE TRIM(category) != ''
                GROUP BY category
                ORDER BY business_count DESC
                LIMIT 10
                """.strip(),
                "Fast path: top business categories",
            ),
        ),
    ]

    for matched, plan in patterns:
        if matched:
            logger.info("llm.fast_path summary=%s prompt=%r", plan.summary, prompt_clean)
            return plan
    return None
